management:
  endpoint:
    health:
      show-components: always
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${ABC:10000}
  shutdown: graceful
spring:
  application:
    name: order
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    config:
      retry:
        initial-interval: 1000
    loadbalancer:
      retry:
        max-retries-on-next-service-instance: 2
        max-retries-on-same-service-instance: 0
        retry-on-all-operations: true
        retry-on-all-exceptions: true
resilience4j:
  retry:
    instances:
      payment-retry:
        base-config: base1
        retry-exception-predicate: org.training.turkcell.msorder.resilience.MyRetryPredicate
        result-predicate: org.training.turkcell.msorder.resilience.MyResultPredicate
    configs:
      base1:
        max-attempts: 2
        wait-duration: '1ms'
        exponential-backoff-multiplier: 3
        enable-exponential-backoff: true
        exponential-max-wait-duration: '10ms'
  circuitbreaker:
    instances:
      payment-cb:
        sliding-window-type: count_based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 10
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: false
        slow-call-duration-threshold: 500ms
        slow-call-rate-threshold: 30